# Generated by Django 4.0.3 on 2022-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0003_alter_projet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
