# Generated by Django 4.0.3 on 2022-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0009_alter_enseigne_options_alter_projet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilite',
            name='acces',
            field=models.CharField(choices=[('Public', 'Public'), ('Privé', 'Privé')], default='Privé', max_length=255, verbose_name='Accessibilité Parking'),
        ),
        migrations.AlterField(
            model_name='mobilite',
            name='borne',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255, verbose_name='Option Borne'),
        ),
        migrations.AlterField(
            model_name='mobilite',
            name='km_an_vehicule_fonction',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de km/an véhicule de fonction'),
        ),
        migrations.AlterField(
            model_name='mobilite',
            name='km_an_vehicule_utilitaire',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de km/an véhicule utilitaires'),
        ),
        migrations.AlterField(
            model_name='mobilite',
            name='parking',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=255, verbose_name='Présence parking '),
        ),
        migrations.AlterField(
            model_name='mobilite',
            name='pt_de_charge',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de point de charges desirés'),
        ),
    ]
