# Generated by Django 4.0.3 on 2022-06-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0012_remove_ensolleilement_prix_coeff_1_35_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourbeChargePerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du profil')),
                ('type', models.CharField(choices=[('Ouvré', 'Ouvré'), ('Weekend', 'Weekend')], max_length=255, verbose_name='Jour')),
                ('coeff_0', models.FloatField(default=20, verbose_name='00:00 (%)')),
                ('coeff_1', models.FloatField(default=20, verbose_name='01:00 (%)')),
                ('coeff_2', models.FloatField(default=20, verbose_name='02:00')),
                ('coeff_3', models.FloatField(default=20, verbose_name='03:00')),
                ('coeff_4', models.FloatField(default=20, verbose_name='04:00')),
                ('coeff_5', models.FloatField(default=20, verbose_name='05:00')),
                ('coeff_6', models.FloatField(default=20, verbose_name='06:00')),
                ('coeff_7', models.FloatField(default=20, verbose_name='07:00')),
                ('coeff_8', models.FloatField(default=20, verbose_name='08:00')),
                ('coeff_9', models.FloatField(default=20, verbose_name='09:00')),
                ('coeff_10', models.FloatField(default=20, verbose_name='10:00')),
                ('coeff_11', models.FloatField(default=20, verbose_name='11:00')),
                ('coeff_12', models.FloatField(default=20, verbose_name='12:00')),
                ('coeff_13', models.FloatField(default=20, verbose_name='13:00')),
                ('coeff_14', models.FloatField(default=20, verbose_name='14:00')),
                ('coeff_15', models.FloatField(default=20, verbose_name='15:00')),
                ('coeff_16', models.FloatField(default=20, verbose_name='16:00')),
                ('coeff_17', models.FloatField(default=20, verbose_name='17:00')),
                ('coeff_18', models.FloatField(default=20, verbose_name='18:00')),
                ('coeff_19', models.FloatField(default=20, verbose_name='19:00')),
                ('coeff_20', models.FloatField(default=20, verbose_name='20:00')),
                ('coeff_21', models.FloatField(default=20, verbose_name='21:00')),
                ('coeff_22', models.FloatField(default=20, verbose_name='22:00')),
                ('coeff_23', models.FloatField(default=20, verbose_name='23:00')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.projet', verbose_name='Projet')),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
    ]
