# Generated by Django 4.0.3 on 2022-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0014_profilperso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courbechargeperso',
            name='name',
            field=models.CharField(default='-', max_length=255, verbose_name='Nom du profil'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='type',
            field=models.CharField(choices=[('Ouvré', 'Ouvré'), ('Weekend', 'Weekend')], default='Ouvré', max_length=255, verbose_name='Jour'),
        ),
    ]
