# Generated by Django 4.0.3 on 2022-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0015_alter_courbechargeperso_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_0',
            field=models.FloatField(default=19, verbose_name='00:00 (%)'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_1',
            field=models.FloatField(default=18, verbose_name='01:00 (%)'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_10',
            field=models.FloatField(default=100, verbose_name='10:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_11',
            field=models.FloatField(default=93, verbose_name='11:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_12',
            field=models.FloatField(default=87, verbose_name='12:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_13',
            field=models.FloatField(default=81, verbose_name='13:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_14',
            field=models.FloatField(default=83, verbose_name='14:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_15',
            field=models.FloatField(default=83, verbose_name='15:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_16',
            field=models.FloatField(default=69, verbose_name='16:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_17',
            field=models.FloatField(default=44, verbose_name='17:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_18',
            field=models.FloatField(default=25, verbose_name='18:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_19',
            field=models.FloatField(default=22, verbose_name='19:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_2',
            field=models.FloatField(default=18, verbose_name='02:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_21',
            field=models.FloatField(default=18, verbose_name='21:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_22',
            field=models.FloatField(default=18, verbose_name='22:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_23',
            field=models.FloatField(default=18, verbose_name='23:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_3',
            field=models.FloatField(default=19, verbose_name='03:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_4',
            field=models.FloatField(default=18, verbose_name='04:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_5',
            field=models.FloatField(default=19, verbose_name='05:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_6',
            field=models.FloatField(default=27, verbose_name='06:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_7',
            field=models.FloatField(default=50, verbose_name='07:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_8',
            field=models.FloatField(default=71, verbose_name='08:00'),
        ),
        migrations.AlterField(
            model_name='courbechargeperso',
            name='coeff_9',
            field=models.FloatField(default=92, verbose_name='09:00'),
        ),
        migrations.AlterField(
            model_name='modulespv',
            name='Surface_Panneau_m2',
            field=models.FloatField(verbose_name='Surface (m²)'),
        ),
    ]
