# Generated by Django 4.0.3 on 2022-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0016_alter_courbechargeperso_coeff_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigne',
            name='nb_sites',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de sites'),
        ),
    ]
