# Generated by Django 4.0.3 on 2022-06-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0017_alter_enseigne_nb_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilperso',
            name='profil',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PV.courbechargeperso', verbose_name='Profil personnalisé'),
        ),
    ]
