# Generated by Django 4.0.3 on 2022-06-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0020_exportsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportsite',
            name='projet',
        ),
    ]
