# Generated by Django 4.0.3 on 2022-06-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0021_remove_exportsite_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsite',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PV.projet', verbose_name='Projet'),
            preserve_default=False,
        ),
    ]
