# Generated by Django 4.0.3 on 2022-06-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0022_exportsite_projet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportsite',
            unique_together={('enseigne',)},
        ),
    ]
