# Generated by Django 4.0.3 on 2022-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0023_alter_exportsite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsite',
            name='sitename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du site'),
        ),
    ]
