# Generated by Django 4.0.3 on 2022-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0024_exportsite_sitename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsite',
            name='sitename',
            field=models.CharField(max_length=255, verbose_name='Nom du site'),
        ),
    ]
