# Generated by Django 4.0.3 on 2022-07-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0026_exportsite_eco_exportsite_eco_mde_exportsite_eco_pv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
