# Generated by Django 4.0.3 on 2022-07-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0027_alter_localisation_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilTypesPerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(max_length=255, verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Profil Type',
            },
        ),
    ]
