# Generated by Django 4.0.3 on 2022-07-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0029_alter_profilperso_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiltypesperso',
            options={'verbose_name': 'Profil Type Perso'},
        ),
        migrations.AlterField(
            model_name='profilperso',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PV.profiltypesperso'),
        ),
    ]
