# Generated by Django 4.0.3 on 2022-05-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
