# Generated by Django 4.0.3 on 2022-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0006_projet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du projet'),
        ),
    ]
