# Generated by Django 4.0.3 on 2022-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0008_alter_enseigne_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseigne',
            options={'verbose_name': 'Site'},
        ),
        migrations.AlterField(
            model_name='projet',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom du projet'),
        ),
    ]
