# Generated by Django 4.0.3 on 2022-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0011_ensolleilement_prix_coeff_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensolleilement',
            name='prix_coeff_1_35',
        ),
        migrations.AlterField(
            model_name='ensolleilement',
            name='prix_coeff_1',
            field=models.FloatField(default=0, verbose_name='Coeff D 1 - Prix en c€ / kWh - 36-100 kWc'),
        ),
        migrations.AlterField(
            model_name='ensolleilement',
            name='prix_coeff_1_1',
            field=models.FloatField(default=0, verbose_name='Coeff D 1.1 - Prix en c€ / kWh - 9-36 kWc'),
        ),
        migrations.AlterField(
            model_name='ensolleilement',
            name='prix_coeff_1_2',
            field=models.FloatField(default=0, verbose_name='Coeff D 1.2 - Prix en c€ / kWh - 3-9 kWc'),
        ),
    ]
