# Generated by Django 4.0.3 on 2022-06-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0013_courbechargeperso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilPerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.batiment', verbose_name='Batiment')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PV.courbechargeperso', verbose_name='Profil personnalisé')),
            ],
        ),
    ]
